<div>
	<ul id="nav">
		<li class="top"><a class="top_link" href="#"><span class="down">Society</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Details</a>
					<ul>
						<li><a href="AptDetailsView.aspx">View Details</a></li>
					</ul>
				</li>
				<li><a href="" class="fly">Flat Details</a>
					<ul>
						<li><a href="ListAllFlat.aspx">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Common Rentals</a>
					<ul>
						<li><a href="#">View Details</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">My Profile</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">My Details</a>
					<ul>
						<li><a href="PersonalDetails.aspx">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Flat Details</a>
					<ul>
						<li><a href="FlatDetails.aspx">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Payment</a>
					<ul>
						<li><a href="#">View Payment</a></li>
						<li><a href="#">Add Payment Details</a></li>
					</ul>
				</li>
			</ul>
		</li>
    <li class="top"><a class="top_link" href="#"><span class="down">Info Centre</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">News</a>
					<ul>
						<li><a href="ViewNews.aspx">View</a></li>
					</ul>
				</li>
		    <li><a href="#" class="fly">Society News</a>
					<ul>
						<li><a href="ViewSocietyNews.aspx">View</a></li>
					</ul>
				</li>	
       <li><a href="#" class="fly">City News</a>
					<ul>
						<li><a href="#">View</a></li>
					</ul>
				</li>	
    </ul>
		</li>

    <li class="top">
      <a class="top_link" href="#">
        <span class="down">Service Request</span>
      </a>
      <ul class="sub">
        <li>
          <a href="#" class="fly">Make Request</a>
          <ul>
            <li>
              <a href="UpdateRequest.aspx">Add Request</a>
            </li>
            <li>
              <a href="ViewNews.aspx">View Status</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="fly">Bill</a>
          <ul>
            <li>
              <a href="#">View</a>
            </li>
          </ul>
        </li>
      </ul>
    </li>
    
		<li class="top"><a class="top_link" href="#"><span class="down">Reports</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Society Expenses</a>
					<ul>
						<li><a href="">Expense Report</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">My Flat Expenses</a>
					<ul>
						<li><a href="">Expense Report</a></li>
					</ul>
				</li>
			</ul>
		</li>
    
    
    <li class="top"><a class="top_link" href="#"><span class="down">City Info</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">ATM Center</a></li>
        <li><a href="#" class="fly">Banks</a></li>
				<li><a href="#" class="fly">Colleges</a></li>
				<li><a href="#" class="fly">Schools</a></li>
        <li><a href="#" class="fly">Hospitals</a></li>
        <li><a href="#" class="fly">Theatres</a></li>
			
			</ul>
		</li>
  <li class="top"><a class="top_link" href=""><span class="down">Automation</span></a>
			<ul class="sub">
				<li><a href="http://192.168.0.102" class="fly">View</a></li>
					</ul>
		</li>
	</ul>
</div>

