<div>
	<ul id="nav">
		<li class="top"><a class="top_link" href="#"><span class="down">Administration</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">User Management</a>
					<ul>
						<li><a href="ListAllUsers.aspx">View User </a></li>
            <li><a href="NewSignUp.aspx">New SignUp </a> </li>
						<li><a href="CreateUsers.aspx">Add User </a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">Society</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Details</a>
					<ul>
						<li><a href="AptDetailsView.aspx">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Flat Details</a>
					<ul>
						<li><a href="ListAllFlats.aspx">View Details</a></li>
					</ul>
				</li>
				<li>
          <a href="#" class="fly">Common Rentals</a>
					<ul>
						<li><a href="#">View Details</a></li>
					</ul>
				</li>
			</ul>
		</li>
    <li class="top">
      <a class="top_link" href="#">
        <span class="down">News</span>
      </a>
      <ul class="sub">
        <li>
          <a href="#" class="fly">All News</a>
          <ul>
            <li>
              <a href="UpdateNews.aspx">Update</a>
            </li>
            <li>
              <a href="ViewNews.aspx">View</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" class="fly">Society News</a>
          <ul>
            <li>
              <a href="SocietyNewsUpdate.aspx">Update</a>
            </li>
            <li>
              <a href="ViewSocietyNews.aspx">View</a>
            </li>
          </ul>
        </li>
      </ul>
    </li>
		<li class="top"><a class="top_link" href="#"><span class="down">Service Request</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Requested Service</a>
					<ul>
						<li><a href="AcceptRequest.aspx">View</a></li>
					</ul>
				</li>
				</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">Reports</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Expenses</a>
					<ul>
						<li><a href="#">Expense Report</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Payment</a>
					<ul>
						<li><a href="#">Payment Report</a></li>
					</ul>
				</li>
			</ul>
		</li>
	</ul>
</div>